//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Aufgabenblatt_04.Aufgabe_13.Service.Model" +
        "s")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerServiceProxy.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        bool AddCustomer(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/AddCustomer", ReplyAction="http://tempuri.org/ICustomerService/AddCustomerResponse")]
        System.Threading.Tasks.Task<bool> AddCustomerAsync(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveCustomer", ReplyAction="http://tempuri.org/ICustomerService/RemoveCustomerResponse")]
        bool RemoveCustomer(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/RemoveCustomer", ReplyAction="http://tempuri.org/ICustomerService/RemoveCustomerResponse")]
        System.Threading.Tasks.Task<bool> RemoveCustomerAsync(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomersResponse")]
        System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer> GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer>> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer> GetCustomers(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer>> GetCustomersAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.ICustomerService>, Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCustomer(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter) {
            return base.Channel.AddCustomer(Parameter);
        }
        
        public System.Threading.Tasks.Task<bool> AddCustomerAsync(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter) {
            return base.Channel.AddCustomerAsync(Parameter);
        }
        
        public bool RemoveCustomer(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter) {
            return base.Channel.RemoveCustomer(Parameter);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveCustomerAsync(Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer Parameter) {
            return base.Channel.RemoveCustomerAsync(Parameter);
        }
        
        public System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer> GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer> GetCustomers(string name) {
            return base.Channel.GetCustomers(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Aufgabenblatt_04.Aufgabe_13.Client.CustomerServiceProxy.Customer>> GetCustomersAsync(string name) {
            return base.Channel.GetCustomersAsync(name);
        }
    }
}
