//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaSchoeller.Dublin.Client.Proxies.Fleets
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuisnessUnit", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Models")]
    public partial class BuisnessUnit : object
    {
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Communications.Mo" +
        "dels")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MaSchoeller.Dublin.Client.Proxies.Fleets.SaveOrUpdateBuisnessUnitResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MaSchoeller.Dublin.Client.Proxies.Fleets.DeleteBuisnessUnitResult))]
    public partial class BaseResult : object
    {
        
        private MaSchoeller.Dublin.Client.Proxies.Fleets.OperationResult ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaSchoeller.Dublin.Client.Proxies.Fleets.OperationResult Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveOrUpdateBuisnessUnitResult", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Communications.Mo" +
        "dels")]
    public partial class SaveOrUpdateBuisnessUnitResult : MaSchoeller.Dublin.Client.Proxies.Fleets.BaseResult
    {
        
        private MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit BuisnessUnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit BuisnessUnit
        {
            get
            {
                return this.BuisnessUnitField;
            }
            set
            {
                this.BuisnessUnitField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteBuisnessUnitResult", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Communications.Mo" +
        "dels")]
    public partial class DeleteBuisnessUnitResult : MaSchoeller.Dublin.Client.Proxies.Fleets.BaseResult
    {
        
        private MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit BuisnessUnitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit BuisnessUnit
        {
            get
            {
                return this.BuisnessUnitField;
            }
            set
            {
                this.BuisnessUnitField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Database")]
    public enum OperationResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lock = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SaveFailure = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CascadingDeleteError = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyExists = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthorized = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthenticated = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnkownError = 2147483647,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaSchoeller.Dublin.Client.Proxies.Fleets.IFleetService")]
    public interface IFleetService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/DeleteBuisnessUnit", ReplyAction="http://tempuri.org/IFleetService/DeleteBuisnessUnitResponse")]
        MaSchoeller.Dublin.Client.Proxies.Fleets.DeleteBuisnessUnitResult DeleteBuisnessUnit(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/DeleteBuisnessUnit", ReplyAction="http://tempuri.org/IFleetService/DeleteBuisnessUnitResponse")]
        System.Threading.Tasks.Task<MaSchoeller.Dublin.Client.Proxies.Fleets.DeleteBuisnessUnitResult> DeleteBuisnessUnitAsync(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SaveOrUpdateBuisnessUnit", ReplyAction="http://tempuri.org/IFleetService/SaveOrUpdateBuisnessUnitResponse")]
        MaSchoeller.Dublin.Client.Proxies.Fleets.SaveOrUpdateBuisnessUnitResult SaveOrUpdateBuisnessUnit(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SaveOrUpdateBuisnessUnit", ReplyAction="http://tempuri.org/IFleetService/SaveOrUpdateBuisnessUnitResponse")]
        System.Threading.Tasks.Task<MaSchoeller.Dublin.Client.Proxies.Fleets.SaveOrUpdateBuisnessUnitResult> SaveOrUpdateBuisnessUnitAsync(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/GetAllBuisnessUnits", ReplyAction="http://tempuri.org/IFleetService/GetAllBuisnessUnitsResponse")]
        System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit> GetAllBuisnessUnits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/GetAllBuisnessUnits", ReplyAction="http://tempuri.org/IFleetService/GetAllBuisnessUnitsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit>> GetAllBuisnessUnitsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IFleetServiceChannel : MaSchoeller.Dublin.Client.Proxies.Fleets.IFleetService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class FleetServiceClient : System.ServiceModel.ClientBase<MaSchoeller.Dublin.Client.Proxies.Fleets.IFleetService>, MaSchoeller.Dublin.Client.Proxies.Fleets.IFleetService
    {
        
        public FleetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public MaSchoeller.Dublin.Client.Proxies.Fleets.DeleteBuisnessUnitResult DeleteBuisnessUnit(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit)
        {
            return base.Channel.DeleteBuisnessUnit(buisnessUnit);
        }
        
        public System.Threading.Tasks.Task<MaSchoeller.Dublin.Client.Proxies.Fleets.DeleteBuisnessUnitResult> DeleteBuisnessUnitAsync(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit)
        {
            return base.Channel.DeleteBuisnessUnitAsync(buisnessUnit);
        }
        
        public MaSchoeller.Dublin.Client.Proxies.Fleets.SaveOrUpdateBuisnessUnitResult SaveOrUpdateBuisnessUnit(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit)
        {
            return base.Channel.SaveOrUpdateBuisnessUnit(buisnessUnit);
        }
        
        public System.Threading.Tasks.Task<MaSchoeller.Dublin.Client.Proxies.Fleets.SaveOrUpdateBuisnessUnitResult> SaveOrUpdateBuisnessUnitAsync(MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit buisnessUnit)
        {
            return base.Channel.SaveOrUpdateBuisnessUnitAsync(buisnessUnit);
        }
        
        public System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit> GetAllBuisnessUnits()
        {
            return base.Channel.GetAllBuisnessUnits();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Fleets.BuisnessUnit>> GetAllBuisnessUnitsAsync()
        {
            return base.Channel.GetAllBuisnessUnitsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
