//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaSchoeller.Dublin.Client.Proxies.Calculations
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleMonthCost", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Models")]
    public partial class VehicleMonthCost : object
    {
        
        private double CostsField;
        
        private int CountField;
        
        private System.DateTime MonthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costs
        {
            get
            {
                return this.CostsField;
            }
            set
            {
                this.CostsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessUnitMonthCost", Namespace="http://schemas.datacontract.org/2004/07/MaSchoeller.Dublin.Core.Models")]
    public partial class BusinessUnitMonthCost : object
    {
        
        private string BusinessUnitField;
        
        private double CostsField;
        
        private System.DateTime MonthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessUnit
        {
            get
            {
                return this.BusinessUnitField;
            }
            set
            {
                this.BusinessUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Costs
        {
            get
            {
                return this.CostsField;
            }
            set
            {
                this.CostsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaSchoeller.Dublin.Client.Proxies.Calculations.ICalculationService")]
    public interface ICalculationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/GetCalculationMonthSets", ReplyAction="http://tempuri.org/ICalculationService/GetCalculationMonthSetsResponse")]
        System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.VehicleMonthCost> GetCalculationMonthSets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/GetCalculationMonthSets", ReplyAction="http://tempuri.org/ICalculationService/GetCalculationMonthSetsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.VehicleMonthCost>> GetCalculationMonthSetsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/GetCalculationsBusinessUnitSets", ReplyAction="http://tempuri.org/ICalculationService/GetCalculationsBusinessUnitSetsResponse")]
        System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.BusinessUnitMonthCost> GetCalculationsBusinessUnitSets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/GetCalculationsBusinessUnitSets", ReplyAction="http://tempuri.org/ICalculationService/GetCalculationsBusinessUnitSetsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.BusinessUnitMonthCost>> GetCalculationsBusinessUnitSetsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ICalculationServiceChannel : MaSchoeller.Dublin.Client.Proxies.Calculations.ICalculationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CalculationServiceClient : System.ServiceModel.ClientBase<MaSchoeller.Dublin.Client.Proxies.Calculations.ICalculationService>, MaSchoeller.Dublin.Client.Proxies.Calculations.ICalculationService
    {
        
        public CalculationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.VehicleMonthCost> GetCalculationMonthSets()
        {
            return base.Channel.GetCalculationMonthSets();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.VehicleMonthCost>> GetCalculationMonthSetsAsync()
        {
            return base.Channel.GetCalculationMonthSetsAsync();
        }
        
        public System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.BusinessUnitMonthCost> GetCalculationsBusinessUnitSets()
        {
            return base.Channel.GetCalculationsBusinessUnitSets();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MaSchoeller.Dublin.Client.Proxies.Calculations.BusinessUnitMonthCost>> GetCalculationsBusinessUnitSetsAsync()
        {
            return base.Channel.GetCalculationsBusinessUnitSetsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
